package koporscho;
import proto.Prototype;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Koporscho csapat Projlab 
//  @ File Name : Equipment.java
//  @ Date : 2022. 03. 25.
//  @ Authors : Szab� Egon, Bir� Ferenc, T�th B�lint, Ferge M�t�, Rahmi D�niel
//
//


/**
 * A virológusok lehetséges eszközeinek megvalósítására szolgáló osztály.
 */
public class Equipment {

	/** Az adott felszerelés által kifejtett hatás (effekt). */
	private StatusEffect effect = null;

	/** Az adott felszerelés tartóssága*/
	private int durability;

	private String name = "";

	/**
	 * Kontruktor, amely a paraméterként kapott effektel rendelkező tárgyat hozza létre.
	 * @param e
	 */
	public Equipment(StatusEffect e, int d) {
		effect = e;
		durability = d;
	}
	/**
	 * Kontruktor, amely a paraméterként kapott effektel rendelkező tárgyat hozza létre.
	 * @param e
	 */
	public Equipment(StatusEffect e, int d, String n) {
		effect = e;
		durability = d;
		name = n;
	}

	/**
	 * Implicit getter a tárgy effektje számára.
	 * @return A tárgy effektje
	 */
	public StatusEffect GetEffect() {
		return effect;
	}

	/**
	 * Implicit setter a tárgy tartósságának számára.
	 * @param d A tárgy tartóssága
	 */
	public void SetDurability(int d){
		durability = d;
	}

	/**
	 * Implicit getter a tárgy tartósságára.
	 * @return A tárgy tartóssága
	 */
	public int GetDurability(){
		return durability;
	}

	/**
	 * Egy eszköz tartósságát csökkenti és visszaadja azt.
	 * @return A tárgy tartóssága mínusz egy.
	 */
	public int DecreaseDurability(){ return --durability; }

	/**
	 * Implicict getter az eszköt nevének lekérdezéséhez.
	 * @return Az eszköz neve.
	 */
	public String GetName(){
		return name;
	}

	/**
	 * Az Equipment osztály logger fügvénye, mely az adott eszköz tulajdonságait írja ki a standard kimentre és fájlba.
	 * @throws java.io.IOException
	 */
	public void log() throws java.io.IOException{
		System.out.println(Prototype.objectIDs.get(this)+":");
		System.out.println("\tname: " + (name == null || name.isEmpty() ? "-" : name));
		System.out.println("\tdurability: " + durability);
		System.out.println("\teffect: " + Prototype.objectIDs.get(effect));

		Prototype.writer.write(Prototype.objectIDs.get(this)+":"+"\n");
		Prototype.writer.write("\tname: " + (name == null || name.isEmpty() ? "-" : name)+"\n");
		Prototype.writer.write("\tdurability: " + durability+"\n");
		Prototype.writer.write("\teffect: " + Prototype.objectIDs.get(effect)+"\n");
	}
}
