package koporscho;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Koporscho csapat Projlab 
//  @ File Name : Materials.java
//  @ Date : 2022. 03. 25.
//  @ Authors : Szab� Egon, Bir� Ferenc, T�th B�lint, Ferge M�t�, Rahmi D�niel
//
//


import proto.Prototype;

/** Az anyagok tárolásáért felelős osztály. */
public class Materials {
	private int nucleotide;
	private int aminoAcid;

	/**
	 * Materials objektum konstruktora.
	 */
	public Materials() {
		nucleotide = 0;
		aminoAcid = 0;
	}

	/**
	 * A Materials osztály két paraméteres konstruktora.
	 * @param nucleotide Nukleotid szám
	 * @param aminoAcid Aminosav szám
	 */
	public Materials(int nucleotide, int aminoAcid){
		this.nucleotide = nucleotide;
		this.aminoAcid = aminoAcid;
	}

	/**
	 * A Materials osztály másoló konstruktora.
	 * @param m Másolandó Material objektum
	 */
	public Materials(Materials m) {
		nucleotide = m.nucleotide;
		aminoAcid = m.aminoAcid;

		if(Prototype.objectIDs.containsKey(m)) {
			String id = Prototype.objectIDs.get(m);
			String base = id;
			for(int i = 1; i < 10; i++) {
				id = base+"_"+i;
				if(!Prototype.objectIDs.containsValue(id))
					break;
			}
			Prototype.objectIDs.put(this, id);
			Prototype.objectIDsInv.put(id, this);
		}
	}


	/**
	 *  Igazzal tér vissza, ha a paraméterként kapott anyagokból el lehet elkészíteni az adott ágenst.
	 * @param m Rendelkezésre álló anyagok.
	 * @return Elegendő anyag áll-e rendelkezésre.
	 */
	public boolean CanCraft(Materials m) {
		return this.GetAminoAcid() >= m.GetAminoAcid() && this.GetNucleotide() >= m.GetNucleotide();
	}

	/**
	 * Implicit getter az anyagban található nucleotidok számára.
	 * @return Nucleotidok száma.
	 */
	public int GetNucleotide(){
		return nucleotide;
	}

	/**
	 * Implicit getter az anyagban található aminosavak számára.
	 * @return Aminosavak száma.
	 */
	public int GetAminoAcid(){
		return aminoAcid;
	}

	/**
	 * Az anyagban található nucleotidok számát settelő függvény.
	 * @param nucleotide Nucleotidok új száma
	 */
	public void SetNucleotide(int nucleotide){
		this.nucleotide = nucleotide;
	}

	/**
	 * Az anyagban található aminosavak számát settelő függvény.
	 * @param aminoAcid Aminosavak új száma
	 */
	public void SetAminoAcid(int aminoAcid){
		this.aminoAcid = aminoAcid;
	}

}
